// Generated by CoffeeScript 1.6.2
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $(document).ready(function() {
    var key;

    key = 'CTRL';
    $('#bookmarkme').click(function() {
      if (window.sidebar && window.sidebar.addPanel) {
        return window.sidebar.addPanel(document.title, window.location.href, '');
      } else if (window.external && (__indexOf.call(window.external, 'AddFavorite') >= 0)) {
        return window.external.AddFavorite(location.href, document.title);
      } else if (window.opera && window.print) {
        this.title = document.title;
        return true;
      } else {
        return alert('Нажмите ' + key + ' + D, чтобы добавить в избранное.');
      }
    });
    $('.names a').click(function() {
      var rel;

      rel = $(this).data('rel');
      $('.reviewer').hide();
      $('.names a').removeClass('initial');
      $('.names a').removeClass('active');
      $(this).addClass('active');
      $(rel).show();
      $('#ob_overlay').show();
      $('.ytvideo').hide();
      return false;
    });
    return $('a.close_reviewer, #ob_overlay').click(function() {
      $('.names a').removeClass('active');
      $('.names a').addClass('initial');
      $('.reviewer').hide();
      $('#ob_overlay').hide();
      $('.ytvideo').show();
      return false;
    });
  });

}).call(this);
